### ISSUE TITLE
XAML Designer is not loading

### ISSUE THREAD

**Issue by rvxfahim** [tugsadhk/WinUI3-Serial-Port-Communication#1]
Were you able to use the xaml drag and drop designer for the UI? The designer doesn't load in my case.

**Comment by tugsadhk** [comment]
Hi, first of all thank you for using my project, but unfortunately WinUI3
does not support drag n drop designer yet, you have to use xaml codes for
the design anything. If you have any other questions please let me know and
have a nice day.
